### ISSUE TITLE
How to log in and pull my first data from Garmin?

### ISSUE THREAD

**Issue by algerza** [petergardfjall/garminexport#65]
First of all, thank you very much for building this library - it has great potential to analyze your personal fitness data on a daily basis with further insights than Garmin provides! 

Yet the extraction looks reasonable, I'm a bit lost on how to log in with my credentials. Would you be able to indicate how to log in for the first time and pull the first chunk of data please @petergardfjall ? It would be highly appreciated. Again - thanks for your great work!

**Comment by petergardfjall** [comment]
Have you tried following these instructions: https://github.com/petergardfjall/garminexport#as-a-command-line-tool-garmin-backup?

- get a working Python installation
- install `garminexport`: `pip install garminexport`
- run garminexport: `garmin-backup --backup-dir=<directory-of-your-choice> <username or email>`. you will be prompted for your password. If you want to supply the password directly, also add a `--password <your-password>` flag to the command-line.

The first run of `garmin-backup` will back up _all_ of your activities. The next time you run it, it runs incrementally (only activities added since your last backup are added to the backup directory).
