### ISSUE TITLE
authentication failure

### ISSUE THREAD

**Issue by peemot** [petergardfjall/garminexport#76]
The script stopped working a day or two ago.
> [ERROR] failed with exception: authentication failure: did you enter valid credentials?

**Comment by zxxxh** [comment]
Confirmed - I have receive the same message. Debug shows additional messages:

> Access denied
> This website is using a security service to protect itself from online attacks.

**Comment by random1781** [comment]
Garmin seems to be blocking requests based on the provided User-Agent. I now get an authentication failure error with the following debug message:

```
  <p>This website is using a security service to protect itself from online attacks.</p>
  <ul class="cferror_details">
    <li>Ray ID: rayid</li>
    <li>Timestamp: 2021-05-07 13:11:38 UTC</li>
    <li>Your IP address: #.#.#.#</li>
    <li class="XXX_no_wrap_overflow_hidden">Requested URL: sso.garmin.com/sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F&amp;gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso </li>
    <li>Error reference number: 1020</li>
    <li>Server ID: FL_16F223</li>
    <li>User-Agent: python-requests/2.25.1</li>
  </ul>
```

If I add a defined User-Agent of a browser to the request, the authentication succeeds and my activities are downloaded as expected.

I'm not sure if this is a temporary or long-term problem, but I added fake-useragent to generate a User-Agent for long term.

**Comment by zxxxh** [comment]
Garmin has a history of making changes that break third-party client access. This is indeed a user-agent issue, and changing the user-agent string bypasses the issue. Perhaps dev could incorporate fake-useragent to solve this moving forward.

**Comment by pavlinux** [comment]
````diff
diff --git a/garminexport/garminclient.py b/garminexport/garminclient.py
index 2ac4674..45ef6aa 100755
--- a/garminexport/garminclient.py
+++ b/garminexport/garminclient.py
@@ -118,7 +118,8 @@ class GarminClient(object):
             "embed": "false",
             "_csrf": self._get_csrf_token(),
         }
-        headers = {'origin': 'https://sso.garmin.com'}
+        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.134 Safari/537.',
+                   'origin': 'https://sso.garmin.com'}
         auth_response = self.session.post(
             SSO_SIGNIN_URL, headers=headers, params=self._auth_params(), data=form_data)
         log.debug("got auth response: %s", auth_response.text)
```

[user-agent.patch.zip](https://github.com/petergardfjall/garminexport/files/6444074/user-agent.patch.zip)

**Comment by pavlinux** [comment]
```diff
diff --git a/garminexport/garminclient.py b/garminexport/garminclient.py
index 2ac4674..5ebbcb4 100755
--- a/garminexport/garminclient.py
+++ b/garminexport/garminclient.py
@@ -14,6 +14,7 @@ from datetime import timedelta, datetime
 from builtins import range
 from functools import wraps
 from io import BytesIO
+import random
 
 import dateutil
 import dateutil.parser
@@ -112,13 +113,17 @@ class GarminClient(object):
     def _authenticate(self):
         log.info("authenticating user ...")
 
+        with open('user-agents.txt', 'r') as f:
+             fakeua = f.readlines()
+
         form_data = {
             "username": self.username,
             "password": self.password,
             "embed": "false",
             "_csrf": self._get_csrf_token(),
         }
-        headers = {'origin': 'https://sso.garmin.com'}
+        headers = {'User-Agent': random.choice(fakeua).replace('\n', ''),
+                   'origin': 'https://sso.garmin.com'}
         auth_response = self.session.post(
             SSO_SIGNIN_URL, headers=headers, params=self._auth_params(), data=form_data)
         log.debug("got auth response: %s", auth_response.text)
```

Put file user-agents.txt into call script directory, for ex. this https://gist.github.com/pzb/b4b6f57144aea7827ae4

**Comment by micky-gee** [comment]
The solution in this pull request https://github.com/petergardfjall/garminexport/pull/77/files works really well.

Nice fake useragent.

**Comment by petergardfjall** [comment]
I've addressed this issue in https://github.com/petergardfjall/garminexport/commit/33b83548675823f8f872a491363dffc9ba091992.

It allows a custom `User-Agent` to be supplied. Either via command-line.
```
garmin-backup --user-agent='Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2811.59 Safari/537.36'
```

If you prefer to rotate user agent, use a tool such as `user_agent`:
```
# installs the ua cli tool
pip install --user user_agent

garmin-backup --user-agent=$(ua)
```
For library clients, one can pass a `user_agent_fn` function that, when called, produces a
`User-Agent` string to be used as `User-Agent` for the remainder of the session.

**Comment by petergardfjall** [comment]
Released `0.4.0` on pypi.org

**Comment by pavlinux** [comment]
Too fat )))

**Comment by pavlinux** [comment]
> --user-agent=$(ua)'

How this work from bash/sh ?

**Comment by petergardfjall** [comment]
@pavlinux how do you mean? That is bash syntax.

**Comment by micky-gee** [comment]
The problem is, that without even additional command line flags, it won't work.  I think a better philosophy to be: command line tool should work with as little flags as possible, the bare minimum being credentials.

So without adding this:
`garmin-backup --user-agent=$(ua)`

It fails.

The other point to think about: this tool has gained sufficient popularity for Garmin to block it.  Which means we're in the game of whack-a-mole with their system administrators.  Potentially triggered by someone hitting the requests too hard? Or maybe them looking to enforce the API interface harder.  If its the former, some good-behaviour rate limiting would also be in order.

Either way, if we use a standard UA, it'll get blocked again.

Also, hi :wave: Garmin. I know the chaps in Kansas are reading these comments too.  We <3 you.

**Comment by micky-gee** [comment]
Sorry, I made my point poorly.

>The problem is, that without even additional command line flags, it won't work.
Read as: without the additional command line flags it likely _won't continue to work_.

How long before Garmin blocks _that_ default user agent?  Remember, again, Garmin saw enough requests from this tool to block it; this is whack-a-mole territory.

**Comment by petergardfjall** [comment]
> The other point to think about: this tool has gained sufficient popularity for Garmin to block it. Which means we're in the game of whack-a-mole with their system administrators. Potentially triggered by someone hitting the requests too hard? Or maybe them looking to enforce the API interface harder. If its the former, some good-behaviour rate limiting would also be in order.

Point taken. Although the idea is flattering in some sense, I mean this tool having gained enough popularity for Garmin to _actively_ try to block it, I'm not sure about that conclusion (maybe I'm too naive). 

Garmin is definitely working on tightening up their API access to try and filter out uninvited guests like this one (I don't know how many times I've rewritten the authentication code to go through yet another weird hoop...), but I'm not sure if they _specifically_ have tried to block this tool, but generally anything that doesn't look like a web-browser (before this change, the `User-Agent` was set to `requests/2.25` or something to that effect, which is a simple give-away). I don't think they can blacklist a popular user-agent like the default one, although they might be using smarter discovery filters that actually _recognize_ the "fingerprints" of that browser (headers to be expected, etc). Obviously they aren't on that level of sophistication (yet), since things are working with the default.

We'll see how things play out. I'll keep your words in mind though. Thanks for commenting.

**Comment by random1781** [comment]
> I'm not sure if they _specifically_ have tried to block this tool

I agree with this. I think this error is actually a function of Cloudflare's filtering and is probably a common sense thing to enable. I would like to think that they're more focused on stopping another multi-million dollar ransom payout than a tool like this.

I script my syncs, so adding a stand-alone UA generator is simple.

**Comment by pavlinux** [comment]
> @pavlinux, что ты имеешь в виду? Это синтаксис bash.



> @pavlinux how do you mean? That is bash syntax.

Sorry? i don't know that ua it's a utility from $PATH

**Comment by pavlinux** [comment]
2021-05-17 20:16:07,948 [ERROR] failed with exception: authentication failure: did you enter valid credentials?

**Comment by micky-gee** [comment]
Looks like its been blocked again… failing out on all number of UAs.

**Comment by zxxxh** [comment]
>  I don't think they can blacklist a popular user-agent like the default one, although they might be using smarter discovery filters that actually _recognize_ the "fingerprints" of that browser (headers to be expected, etc). Obviously they aren't on that level of sophistication (yet), …


It looks like they did get to that point.

I wish Garmin's engineers would work on improving their products instead of preventing customers from backing up their own data.

I'm curious what the fix will end up being. Currently, I cannot authenticate with any UA, including the 'valid' one my browser supplies.

**Comment by pavlinux** [comment]
> I'm curious what the fix will end up being. Currently, I cannot authenticate with any UA, including the 'valid' one my browser supplies.

https://github.com/petergardfjall/garminexport/issues/79#issuecomment-843658546
